---
 - name: create a file and enter the new line to that file
   hosts: ans-client1-42
   tasks:
      - name: create a file
        file: dest=/var/www/html/index.html state=touch
      - name: enter the new line to that file
        lineinfile: dest=/var/www/html/index.html line='i am the akualli'

